### ISSUE TITLE
Update package name

### ISSUE THREAD

**Issue by robertoduessmann** [robertoduessmann/churrascometro#11]
Update root package to "com.rdesenv" (or something else, ideas are welcome :) )

**Comment by AKMohite** [comment]
So you need to change the package name of project?? I will be able to help you.
But if you change package name you won't be able to update the app with new package name on Play store

**Comment by robertoduessmann** [comment]
Nice catch @AshishMohite96 , thanks for letting me know :)
I would suggest to go ahead and I'll update the app on Play store later, once we don't have too many users yet.
Let me know if you have any question or need any help :) 
Btw if you have another idea to the package name feel free, maybe would be better something more meaningful like com.barbecue, etc

**Comment by AKMohite** [comment]
sure for now will change it to com.barbecue

**Comment by AKMohite** [comment]
Have made changes and made pull request

**Comment by robertoduessmann** [comment]
Thanks @AshishMohite96 will check it :+1:

**Comment by robertoduessmann** [comment]
Implemented in https://github.com/robertoduessmann/churrascometro/pull/15
