### ISSUE TITLE
Translate app to English

### ISSUE THREAD

**Issue by robertoduessmann** [robertoduessmann/churrascometro#12]
Currently the app is available only in pt-br, the idea is make it available in English as well.

**Comment by alistairholmes** [comment]
Hi there :wave: I would like to translate your app to English please :smile:

**Comment by robertoduessmann** [comment]
Hey @alistairholmes thanks for the interesting in the project, sure go ahead I would appreciate it :rocket: 
Let me know if you have any question or need any help :)

**Comment by alistairholmes** [comment]
Great Thanks, I'll work on it, and use Google Translate :wink:

**Comment by robertoduessmann** [comment]
done in #16 thanks @alistairholmes :tada:
