### ISSUE TITLE
Extract admob props to properties file

### ISSUE THREAD

**Issue by robertoduessmann** [robertoduessmann/churrascometro#13]
Extract admob props to properties file

**Comment by AKMohite** [comment]
you want to extract api key in gradle properties file??

**Comment by robertoduessmann** [comment]
I'm not sure what would be the best solution, maybe this could be a good idea :+1:  I'm really open to suggestions @AshishMohite96  :)

**Comment by AKMohite** [comment]
I will implement and submit it

**Comment by AKMohite** [comment]
I have added ads key in gradle file.

**Comment by robertoduessmann** [comment]
closes in #18
