### ISSUE TITLE
Convert app to kotlin

### ISSUE THREAD

**Issue by robertoduessmann** [robertoduessmann/churrascometro#14]
I would like to try out to convert this app to kotlin

**Comment by cfsnsalazar** [comment]
I would be interested in helping out, but I want a shirt :) . Can we divide this into at least 4 issues?.

**Comment by nsalazar0429** [comment]
I would like to work in this issue :)

**Comment by robertoduessmann** [comment]
Hi @cfsnsalazar thanks for your interesting :)
Sure go ahead and let me know if you have any question or need any help :rocket:

**Comment by ghost** [comment]
Awesome

**Comment by Aizen741** [comment]
I would Iike to work on this issue! :)

**Comment by robertoduessmann** [comment]
Hey thanks for your interesting @Aizen741 , but @fadeltd already implemented it here
https://github.com/robertoduessmann/churrascometro/pull/17/
You can help me to review his pull request if you would like or either send others suggestions, I'm totally open :)
Thanks again :rocket:
